In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import cross_validate,KFold, RandomizedSearchCV
from sklearn.model_selection import train_test_split

from sklearn.utils import resample

from xgboost import XGBClassifier

In [2]:
# Pre set values for max cols and chart size

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

plt.rcParams["figure.figsize"] = (15,5)

In [3]:
# Read training data

data=pd.read_csv('train_values.csv')
data.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,802906,6,487,12198,2,30,6,5,t,r,n,f,q,t,d,1,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
1,28830,8,900,2812,2,10,8,7,o,r,n,x,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
2,94947,21,363,8973,2,10,5,5,t,r,n,f,x,t,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
3,590882,22,418,10694,2,10,6,5,t,r,n,f,x,s,d,0,1,0,0,0,0,1,1,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
4,201944,11,131,1488,3,30,8,9,t,r,n,f,x,s,d,1,0,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0

In [4]:
# Read table with target variable 

label=pd.read_csv('train_labels.csv')
label.head()

   building_id  damage_grade
0       802906             3
1        28830             2
2        94947             3
3       590882             2
4       201944             3

In [5]:
# Add Target variable to training data 
data['damage']=label['damage_grade']

In [6]:
# Check distribution of target variable to find out if there is class imbaance problem
data['damage'].value_counts()

2    148259
3     87218
1     25124
Name: damage, dtype: int64

In [7]:
# Define X and y variables
X=pd.get_dummies(data.loc[:,:'has_secondary_use_other'])
y=data['damage'].astype(int)

### Light XGBoost

In [8]:
import lightgbm as lgb

In [202]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=48796)

In [203]:
train_data=lgb.Dataset(X_train,label=y_train)

In [220]:
#setting parameters for lightgbm
param = {'num_leaves':1000, 'max_depth':25,'learning_rate':.1,'max_bins':500}
# param['metric'] = ['auc', 'binary_logloss']

In [221]:
#training our model using light gbm
num_round=50
# start=datetime.now()
lgbm=lgb.train(param,train_data,num_round)
# stop=datetime.now()

In [222]:
#predicting on test set
ypred2=lgbm.predict(X_test)
ypred2[0:5]  # showing first 5 predictions

array([1.45102922, 2.80269413, 2.85340592, 2.21149551, 2.21159472])

In [223]:
p=pd.DataFrame(ypred2)

In [224]:
p['Prediction']=p[0].round().astype(int)

In [225]:
p.drop(columns=[0],inplace=True)

In [226]:
accuracy_score(p,y_test)

0.7346779021043423

In [227]:
f1_score(y_test,p,average='micro')

0.7346779021043423

### Train on full dataset

In [228]:
train_data=lgb.Dataset(X,label=y)
#training our model using light gbm
num_round=50
lgbm=lgb.train(param,train_data,num_round)

In [229]:
# Read Test dataset
X_test=pd.read_csv('test_values.csv')

# Predict
ypred2=lgbm.predict(pd.get_dummies(X_test))

In [230]:
result=pd.DataFrame(ypred2)

# Format the prediction as per submission requirement
result['building_id']=X_test['building_id']
result.rename(columns={0:'damage_grade'},inplace=True)
result=result[['building_id','damage_grade']].astype(int)
result.head()

   building_id  damage_grade
0       300051             2
1        99355             2
2       890251             2
3       745817             1
4       421793             2

In [231]:
result.to_csv('result.csv',index=False)

### This model gives 0.7434 F1-score on submitting result on drivendata.com

### Parameter tuning for xgboost

In [8]:
# Parameters for XGboost
n_jobs=[-1]
n_estimators=np.arange(100,1000,100)
learning_rate=[0.03,0.01,0.1]
max_depth=np.arange(10,100,15)

In [9]:
# Param grid for Xgboost

param_grid={'n_jobs':n_jobs,
            'n_estimators':n_estimators,
            'max_depth':max_depth,
            'learning_rate':learning_rate
           }

In [51]:
%%time
# Fit scaled traing data on XGboost Classifier- This step took 17 hours to complete

clf=XGBClassifier()

kf=KFold(n_splits=2,shuffle=True)

rs=RandomizedSearchCV(clf,param_distributions=param_grid,cv=kf,scoring='f1_micro')

rs.fit(X,y)

Wall time: 16h 47min 7s

RandomizedSearchCV(cv=KFold(n_splits=2, random_state=None, shuffle=True),
                   error_score='raise-deprecating',
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1, gamma=0,
                                           learning_rate=0.1, max_delta_step=0,
                                           max_depth=3, min_child_weight=1,
                                           missing=None, n_estimators=100,
                                           n_jobs=1, nthread=None,
                                           objecti...
                                           seed=None, silent=None, subsample=1,
                                           verbosity=1),
                   iid='warn', n_iter=10, n_jobs=None,
                   param_distributions={'learning_rate': [0.03, 0.01, 0.1],
                                        'max_depth': array([10, 25, 40, 55, 70, 85]),
                                        'n_estimators': array([100, 200, 300, 400, 500, 600, 700, 800, 900]),
                                        'n_jobs': [-1]},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring='f1_micro', verbose=0)

In [52]:
rs.best_params_

{'n_jobs': -1, 'n_estimators': 600, 'max_depth': 10, 'learning_rate': 0.1}

In [10]:
# Initiate classifier using best params selected after grid search
clf=XGBClassifier(n_jobs=-1,n_estimators= 600, max_depth= 10,learning_rate= 0.1)

In [11]:
# Train on full training data
clf.fit(X,y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=10,
              min_child_weight=1, missing=None, n_estimators=600, n_jobs=-1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [13]:
# Read Test dataset
X_test=pd.read_csv('test_values.csv')
X_test.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,300051,17,596,11307,3,20,7,6,t,r,n,f,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
1,99355,6,141,11987,2,25,13,5,t,r,n,f,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,1,1,0,0,0,0,0,0,0,0,0
2,890251,22,19,10044,2,5,4,5,t,r,n,f,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
3,745817,26,39,633,1,0,19,3,t,r,x,v,j,t,d,0,0,0,0,0,1,0,0,0,0,0,v,2,1,0,0,1,0,0,0,0,0,0,0
4,421793,17,289,7970,3,15,8,7,t,r,q,f,q,t,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0

In [14]:
# Predict for test dataset
prediction=clf.predict((pd.get_dummies(X_test)))

In [15]:
result=pd.DataFrame(prediction)

In [16]:
# Format the prediction as per submission requirement
result['building_id']=X_test['building_id']
result.rename(columns={0:'damage_grade'},inplace=True)
result=result[['building_id','damage_grade']]
result.head()

   building_id  damage_grade
0       300051             3
1        99355             2
2       890251             2
3       745817             1
4       421793             3

In [18]:
result.to_csv('result.csv',index=False)

### This model gives 0.7434 F1-score on submitting result on drivendata.com

I tried parameter tuning for Random Forest with below param grid but it got to 0.5514 F1-score only.